# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yajnas',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
