# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20180617_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('small_don', models.IntegerField()),
                ('vedic_don', models.IntegerField()),
            ],
        ),
    ]
