# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_mantras'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantras',
            name='basic',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mantras',
            name='note',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='mantras',
            name='qualities',
            field=models.CharField(default='', max_length=250),
        ),
    ]
