# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-22 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20180711_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rudraksh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField()),
                ('planet', models.CharField(default='', max_length=10)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
