# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_rudtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rudraksh',
        ),
    ]
